package com.cn.pojo;
// Generated 2018-11-14 21:02:53 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Access generated by hbm2java
 */
@Entity
@Table(name = "access")
public class Access implements java.io.Serializable {

	private Integer accessId;
	private Commditys commditys;
	private Users users;
	private String accessContext;
	private Integer accessStar;
	private Date accessTime;

	public Access() {
	}

	public Access(Commditys commditys, Users users, String accessContext, Integer accessStar, Date accessTime) {
		this.commditys = commditys;
		this.users = users;
		this.accessContext = accessContext;
		this.accessStar = accessStar;
		this.accessTime = accessTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "accessId", unique = true, nullable = false)
	public Integer getAccessId() {
		return this.accessId;
	}

	public void setAccessId(Integer accessId) {
		this.accessId = accessId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "commdityId")
	public Commditys getCommditys() {
		return this.commditys;
	}

	public void setCommditys(Commditys commditys) {
		this.commditys = commditys;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userId")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "accessContext")
	public String getAccessContext() {
		return this.accessContext;
	}

	public void setAccessContext(String accessContext) {
		this.accessContext = accessContext;
	}

	@Column(name = "accessStar")
	public Integer getAccessStar() {
		return this.accessStar;
	}

	public void setAccessStar(Integer accessStar) {
		this.accessStar = accessStar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "accessTime", length = 0)
	public Date getAccessTime() {
		return this.accessTime;
	}

	public void setAccessTime(Date accessTime) {
		this.accessTime = accessTime;
	}

}
