package com.cn.pojo;
// Generated 2018-11-14 14:43:38 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Commditype generated by hbm2java
 */
@Entity
@Table(name = "commditype", catalog = "shop")
public class Commditype implements java.io.Serializable {

	private Integer commdiTypeId;
	private String commdiTypeName;
	private Set<Commditys> commdityses = new HashSet<Commditys>(0);

	public Commditype() {
	}

	public Commditype(String commdiTypeName, Set<Commditys> commdityses) {
		this.commdiTypeName = commdiTypeName;
		this.commdityses = commdityses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "commdiTypeId", unique = true, nullable = false)
	public Integer getCommdiTypeId() {
		return this.commdiTypeId;
	}

	public void setCommdiTypeId(Integer commdiTypeId) {
		this.commdiTypeId = commdiTypeId;
	}

	@Column(name = "commdiTypeName")
	public String getCommdiTypeName() {
		return this.commdiTypeName;
	}

	public void setCommdiTypeName(String commdiTypeName) {
		this.commdiTypeName = commdiTypeName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "commditype")
	@OrderBy("commdityId asc")
	public Set<Commditys> getCommdityses() {
		return this.commdityses;
	}

	public void setCommdityses(Set<Commditys> commdityses) {
		this.commdityses = commdityses;
	}

}
