package com.cn.pojo;
// Generated 2018-11-14 14:43:38 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name = "images", catalog = "shop")
public class Images implements java.io.Serializable {

	private Integer imageId;
	private Commditys commditys;
	private String imageUrl;
	private Integer imageType;

	public Images() {
	}

	public Images(Commditys commditys, String imageUrl, Integer imageType) {
		this.commditys = commditys;
		this.imageUrl = imageUrl;
		this.imageType = imageType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "imageId", unique = true, nullable = false)
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "commdityId")
	public Commditys getCommditys() {
		return this.commditys;
	}

	public void setCommditys(Commditys commditys) {
		this.commditys = commditys;
	}

	@Column(name = "imageUrl")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "imageType")
	public Integer getImageType() {
		return this.imageType;
	}

	public void setImageType(Integer imageType) {
		this.imageType = imageType;
	}

}
