package com.cn.pojo;
// Generated 2018-11-14 14:43:38 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "shop")
public class Orders implements java.io.Serializable {

	private int orderId;
	private Users users;
	private String address;
	private String receiver;
	private String mobile;
	private String userMessage;
	private Date createDate;
	private Integer status;
	private Double countPrice;
	private Set<Orderitems> orderitemses = new HashSet<Orderitems>(0);

	public Orders() {
	}

	public Orders(int orderId) {
		this.orderId = orderId;
	}

	public Orders(int orderId, Users users, String address, String receiver, String mobile, String userMessage,
			Date createDate, Integer status, Set<Orderitems> orderitemses) {
		this.orderId = orderId;
		this.users = users;
		this.address = address;
		this.receiver = receiver;
		this.mobile = mobile;
		this.userMessage = userMessage;
		this.createDate = createDate;
		this.status = status;
		this.orderitemses = orderitemses;
	}

	@Id

	@Column(name = "orderId", unique = true, nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userId")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	@Column(name="countPrice")
	public Double getCountPrice() {
		return countPrice;
	}

	public void setCountPrice(Double countPrice) {
		this.countPrice = countPrice;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "receiver")
	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	@Column(name = "mobile")
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "userMessage")
	public String getUserMessage() {
		return this.userMessage;
	}

	public void setUserMessage(String userMessage) {
		this.userMessage = userMessage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "orders")
	public Set<Orderitems> getOrderitemses() {
		return this.orderitemses;
	}

	public void setOrderitemses(Set<Orderitems> orderitemses) {
		this.orderitemses = orderitemses;
	}

}
