package com.cn.pojo;
// Generated 2018-11-14 21:02:53 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orderitems generated by hbm2java
 */
@Entity
@Table(name = "orderitems", catalog = "shop")
public class Orderitems implements java.io.Serializable {

	private Integer orderitemsId;
	private Orders orders;
	private Commditys commditys;
	private Users users;
	private int number;

	public Orderitems() {
	}

	public Orderitems(Orders orders, Commditys commditys, Users users, int number) {
		this.orders = orders;
		this.commditys = commditys;
		this.users = users;
		this.number = number;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "orderitemsId", unique = true, nullable = false)
	public Integer getOrderitemsId() {
		return this.orderitemsId;
	}

	public void setOrderitemsId(Integer orderitemsId) {
		this.orderitemsId = orderitemsId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "orderId", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "commdityId", nullable = false)
	public Commditys getCommditys() {
		return this.commditys;
	}

	public void setCommditys(Commditys commditys) {
		this.commditys = commditys;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

}
