package com.cn.pojo;
// Generated 2018-11-14 14:43:38 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Shoppingcar generated by hbm2java
 */
@Entity
@Table(name = "shoppingcar", catalog = "shop")
public class Shoppingcar implements java.io.Serializable {

	private int shoppingCarId;
	private Commditys commditys;
	private Users users;
	private Integer number;

	public Shoppingcar() {
	}

	public Shoppingcar(int shoppingCarId) {
		this.shoppingCarId = shoppingCarId;
	}
	

	public Shoppingcar(Commditys commditys, Users users, Integer number) {
		super();
		this.commditys = commditys;
		this.users = users;
		this.number = number;
	}

	public Shoppingcar(int shoppingCarId, Commditys commditys, Users users, Integer number) {
		this.shoppingCarId = shoppingCarId;
		this.commditys = commditys;
		this.users = users;
		this.number = number;
	}

	@Id

	@Column(name = "shoppingCarId", unique = true, nullable = false)
	public int getShoppingCarId() {
		return this.shoppingCarId;
	}

	public void setShoppingCarId(int shoppingCarId) {
		this.shoppingCarId = shoppingCarId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "commdityId")
	public Commditys getCommditys() {
		return this.commditys;
	}

	public void setCommditys(Commditys commditys) {
		this.commditys = commditys;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userId")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
